# Generated by Django 3.1.1 on 2020-09-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20200912_1446'),
        ('users', '0002_auto_20200912_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='panel.Course'),
        ),
    ]
